# Generated by Django 5.0.7 on 2024-08-17 18:38

import django.db.models.deletion
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to=users.models.user_directory_path)),
                ('profile_picture_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('profile_picture_original_name', models.CharField(blank=True, max_length=255)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('alternative_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_ip_public', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_ip_local', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_host', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_os', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_browser', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
