# Generated by Django 5.0.7 on 2024-08-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_cellphone_userprofile_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsApp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
