# Generated by Django 5.0.7 on 2024-07-30 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_alta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('usuario_alta', models.CharField(max_length=255)),
                ('fecha_alta', models.DateField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMagico.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('usuario_alta', models.CharField(max_length=255)),
                ('fecha_alta', models.DateField()),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMagico.empresa')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMagico.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_documento', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('usuario_alta', models.CharField(max_length=255)),
                ('fecha_alta', models.DateField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMagico.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_documento', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('prefijo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('usuario_alta', models.CharField(max_length=255)),
                ('fecha_alta', models.DateField()),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMagico.cargos')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMagico.empresa')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMagico.estado')),
            ],
        ),
    ]
