# Generated by Django 5.0.7 on 2024-07-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMagico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='id_estado',
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
