# Generated by Django 5.0.7 on 2024-07-31 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMagico', '0002_estado_id_estado_alter_estado_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigo_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppMagico.tipo_documento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_documento',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
