# Generated by Django 5.0.7 on 2024-07-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMagico', '0003_empresa_codigo_documento_empresa_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_documento',
            name='codigo_documento',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
