# Generated by Django 5.0.7 on 2024-07-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMagico', '0004_alter_tipo_documento_codigo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='numero_documento',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
